name: knee_dl_app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.3
  - pandas=1.5.0
  - matplotlib=3.6
  - scikit-learn=1.1.2
  - seaborn=0.11.2
  - tensorflow=2.10.0
  - keras
  - h5py
  - pillow
  - jupyter=1.0.0
  - pip=22.3.1
  - pip:
      - streamlit
      - grad-cam
